name: Artifacts sample

on:
  pull_request:

# https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action
jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - run: echo ${{needs.first.outputs.output1}} ${{needs.first.outputs.output2}}
