name: Run Build
on:
  pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/npm-cache
      - name: Run Build
        run: npm run build
